import type { Metadata } from "next";
import { Urbanist, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cumbre | Bachilleres UAQ",
  description: "Generated by create next app",
};

// Base path for GitHub Pages (must match next.config.ts basePath)
export const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "/cumbre-bachilleres";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} ${ibmPlexSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
